dist: xenial
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

env:
 - REQUESTS="requests" # latest
 - REQUESTS="requests==2.5" # min version of requests library

install: pip install $REQUESTS

script: python setup.py test
