language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
 - REQUESTS="requests" # latest
 - REQUESTS="requests==2.5" # min version of requests library

install: pip install $REQUESTS pytz

script: python setup.py test
