dist: xenial
language: python
os: linux

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

jobs:
  include:
    - python: "3.8"
      env:
      - REQUESTS="requests" # latest

env:
 - REQUESTS="requests" # latest

install: pip install $REQUESTS

script: python setup.py test
