version: 2.1

aliases:
  - &with-requests
    environment:
      REQUESTS: requests
  - &lint
    steps:
      - checkout
      - run: make ci-lint
  - &job-defaults
    steps:
      - checkout
      - run: pip install $REQUESTS
      - run: make test

jobs:
  lint-sdk:
    docker:
      - image: circleci/python:3.10
        <<: *with-requests
    <<: *lint
  python-3_6:
    docker:
      - image: circleci/python:3.6
        <<: *with-requests
    <<: *job-defaults
  python-3_7:
    docker:
      - image: circleci/python:3.7
        <<: *with-requests
    <<: *job-defaults
  python-3_8:
    docker:
      - image: circleci/python:3.8
        <<: *with-requests
    <<: *job-defaults
  python-3_9:
    docker:
      - image: circleci/python:3.9
        <<: *with-requests
    <<: *job-defaults
  python-3_10:
    docker:
      - image: circleci/python:3.10
        <<: *with-requests
    <<: *job-defaults
workflows:
  main:
    jobs:
      - lint-sdk
      - python-3_4
      - python-3_5
      - python-3_6
      - python-3_7
      - python-3_8
      - python-3_9
